"""initial_schema

Revision ID: 185787b8e3bd
Revises: 
Create Date: 2026-05-30 21:29:52.903806
"""
from alembic import op
import sqlalchemy as sa



revision = '185787b8e3bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('anonymous_device_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_anonymous_device_id'), 'users', ['anonymous_device_id'], unique=True)
    op.create_table('video_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=False),
    sa.Column('creator_name', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_sources_scenario'), 'video_sources', ['scenario'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('core_micro_action', sa.JSON(), nullable=False),
    sa.Column('why_worth_doing', sa.Text(), nullable=False),
    sa.Column('action_tips', sa.JSON(), nullable=False),
    sa.Column('use_cases', sa.JSON(), nullable=False),
    sa.Column('precautions', sa.JSON(), nullable=False),
    sa.Column('risk', sa.JSON(), nullable=False),
    sa.Column('graph_id', sa.String(length=64), nullable=False),
    sa.Column('recommended_duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_graph_id'), 'analysis_results', ['graph_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_scenario'), 'analysis_results', ['scenario'], unique=False)
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_video_id'), 'analysis_results', ['video_id'], unique=False)
    op.create_table('analysis_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analysis_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_analysis_id'), 'analysis_tasks', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_user_id'), 'analysis_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_video_id'), 'analysis_tasks', ['video_id'], unique=False)
    op.create_table('health_graphs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_graphs_video_id'), 'health_graphs', ['video_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('graph_id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['health_graphs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_graph_id'), 'challenges', ['graph_id'], unique=False)
    op.create_index(op.f('ix_challenges_user_id'), 'challenges', ['user_id'], unique=False)
    op.create_index(op.f('ix_challenges_video_id'), 'challenges', ['video_id'], unique=False)
    op.create_table('challenge_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.String(length=96), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('micro_action', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('how_to', sa.JSON(), nullable=False),
    sa.Column('precautions', sa.JSON(), nullable=False),
    sa.Column('graph_node_id', sa.String(length=96), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'day', name='uq_challenge_day')
    )
    op.create_index(op.f('ix_challenge_days_challenge_id'), 'challenge_days', ['challenge_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('challenge_id', sa.String(length=96), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('graph_node_id', sa.String(length=96), nullable=False),
    sa.Column('completed_type', sa.String(length=16), nullable=False),
    sa.Column('optional_note', sa.Text(), nullable=True),
    sa.Column('encouragement', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'day', name='uq_checkin_challenge_day')
    )
    op.create_index(op.f('ix_checkins_challenge_id'), 'checkins', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('challenge_id', sa.String(length=96), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_reports_challenge_id'), 'review_reports', ['challenge_id'], unique=True)
    op.create_index(op.f('ix_review_reports_user_id'), 'review_reports', ['user_id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('challenge_id', sa.String(length=96), nullable=True),
    sa.Column('badge_name', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_challenge_id'), 'rewards', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_rewards_user_id'), 'rewards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewards_user_id'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_challenge_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_review_reports_user_id'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_challenge_id'), table_name='review_reports')
    op.drop_table('review_reports')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_challenge_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_challenge_days_challenge_id'), table_name='challenge_days')
    op.drop_table('challenge_days')
    op.drop_index(op.f('ix_challenges_video_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_user_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_graph_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_health_graphs_video_id'), table_name='health_graphs')
    op.drop_table('health_graphs')
    op.drop_index(op.f('ix_analysis_tasks_video_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_user_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_analysis_id'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    op.drop_index(op.f('ix_analysis_results_video_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_scenario'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_graph_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_video_sources_scenario'), table_name='video_sources')
    op.drop_table('video_sources')
    op.drop_index(op.f('ix_users_anonymous_device_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

